version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: sqlanalytics
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://ijp_user:JbufturibQwmucF0vl62pbzkBW6l1a9f@dpg-d0nimqmuk2gs73c1c6rg-a.oregon-postgres.render.com:5432/ijp
      JWT_SECRET: ${JWT_SECRET:-your-secret-key}
      FLASK_ENV: production
      PORT: 5000
      FRONTEND_URL: ${FRONTEND_URL:-http://15.207.114.204:3000}
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://15.207.114.204:5000
      NODE_ENV: production
    volumes:
      - ./src:/app/src:delegated
      - ./public:/app/public:delegated
      - ./package.json:/app/package.json:delegated
      - ./package-lock.json:/app/package-lock.json:delegated
      - ./tsconfig.json:/app/tsconfig.json:delegated
      - ./vite.config.ts:/app/vite.config.ts:delegated
      - ./postcss.config.js:/app/postcss.config.js:delegated
      - ./tailwind.config.js:/app/tailwind.config.js:delegated
      - ./index.html:/app/index.html:delegated
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local