services:
  # Frontend service
  - type: web
    name: sql-analytics-platform
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://sql-analytics-platform-api.onrender.com/api
      - key: NODE_ENV
        value: production
    dockerContext: .
    dockerCommand: ""
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - tsconfig.json
        - vite.config.ts
        - Dockerfile
        - nginx.conf
        - render.yaml
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: "1; mode=block"
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin

  # Backend service
  - type: web
    name: sql-analytics-platform-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    region: oregon
    plan: free
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://ijp_user:JbufturibQwmucF0vl62pbzkBW6l1a9f@dpg-d0nimqmuk2gs73c1c6rg-a/ijp
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: https://sql-analytics-platform.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
    buildFilter:
      paths:
        - backend/**
        - render.yaml

  # Database service
  - type: postgresql
    name: sql-analytics-db
    plan: free
    ipAllowList: []
    region: oregon
